// components/habits/HabitCardStyles.ts
import { StyleSheet } from 'react-native';

export const habitCardStyles = (colors: any, cardColor?: string) => StyleSheet.create({
  card: {
    borderRadius: 16,
    marginBottom: 12,
    borderWidth: 1.5,
    backgroundColor: colors.background,
    borderColor: cardColor ? cardColor + '40' : colors.border,
    shadowColor: cardColor || '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  cardCompleted: {
    borderColor: cardColor ? cardColor + '25' : colors.border,
  },
  content: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  colorIndicator: {
    width: 5,
    borderTopLeftRadius: 16,
    borderBottomLeftRadius: 16,
    position: 'absolute',
    left: -1,
    top: -1,
    bottom: -1,
  },
  info: {
    flex: 1,
    marginLeft: 12,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  name: {
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    color: colors.textPrimary,
  },
  streakBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    gap: 2,
  },
  streakText: {
    fontSize: 12,
    fontWeight: '600',
  },
  offDayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 6,
    alignSelf: 'flex-start',
    backgroundColor: colors.infoLight,
  },
  offDayText: {
    fontSize: 11,
    fontWeight: '500',
    fontStyle: 'italic',
    color: colors.info,
  },
  frequencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginBottom: 6,
    alignSelf: 'flex-start',
    backgroundColor: colors.infoLight,
  },
  frequencyText: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.info,
  },
  description: {
    fontSize: 14,
    marginBottom: 8,
    color: colors.textSecondary,
  },
  targetProgress: {
    marginBottom: 8,
  },
  targetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  targetLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  targetPercentage: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    overflow: 'hidden',
    backgroundColor: colors.border,
  },
  progressFill: {
    height: '100%',
    borderRadius: 3,
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  achievementText: {
    fontSize: 11,
    fontWeight: '600',
  },
  targetHint: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 8,
    borderLeftWidth: 2,
    backgroundColor: colors.infoLight,
    borderLeftColor: colors.info,
  },
  targetHintText: {
    fontSize: 12,
    fontStyle: 'italic',
    color: colors.info,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '600',
  },
  points: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  checkButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.border,
  },
  partialCheckContainer: {
    position: 'relative',
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  partialCheckText: {
    position: 'absolute',
    fontSize: 9,
    fontWeight: '700',
  },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
  },
  floatingPoints: {
    position: 'absolute',
    top: 16,
    right: 70,
    zIndex: 10,
  },
  floatingPointsText: {
    fontSize: 18,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
});